import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ContentDisplayPanel from "./components/ContentDisplayPanel";
import Navbar from "./components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};



export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="forest">
      <body className={inter.className} style={{ height: "100vh", display: "flex", flexDirection: "column" }}>
          <Navbar />
          <ContentDisplayPanel>{children}</ContentDisplayPanel>
      </body>
    </html>
  );
}
